name: Migrate database schema

on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    name: Run Flyway migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Flyway migrations
        run: |
          docker run --rm \
            --volume ${{ github.workspace }}/migrations:/flyway/sql:ro \
            flyway/flyway:7.12.1-alpine \
            -url="jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0" \
            -user="postgres.ionhmxylsljmvebxvicx" \
            -password="dYVE6!P,T6uzSub" \
            migrate