name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    name: Run Flyway Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Flyway Migration
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/database:/flyway/project \
            flyway/flyway:7.12.1-alpine \
            -locations=filesystem:/flyway/project/schema,filesystem:/flyway/project/repeatables \
            -url="jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}?sslmode=require&prepareThreshold=0" \
            -user="${{ secrets.DB_USER }}" \
            -password="${{ secrets.DB_PASSWORD }}" \
            migrate